apiVersion: v1
kind: ConfigMap
metadata:
  name: billing-config
data:
  ASPNETCORE_ENVIRONMENT: "Development"
  ConnectionStrings__Default: "Server=billing-db,1433;Database=BillingDb;User Id=sa;Password=$(SA_PASSWORD);TrustServerCertificate=True"